### ISSUE TITLE
Shiny app Roadmap

### ISSUE THREAD

**Issue by psolymos** [PredictiveEcology/wbi_shiny#1]
### Server setup

- `$HOST/` static file root will have `index.html` with a general outline and links to follow (apps, methods etc) + 404
- `$HOST/apps/` is static file folder with a list of available apps
- `$HOST/apps/nwt/` will proxy to the Shiny app (other apps later as `$HOST/apps/<appname>/`)
- `$HOST/api/v1`static file assets required for the apps are served from here

### Metadata

The metadata will be provided as a JSON file at the root of the API directory, this will contain all relevant info for navigating the available resources (elements, years, scenarios).

- [x] Process raw project outputs into 250/1000 m resolution raster
- [x] Organize file assets for the API file server
- [x] Process raster to get [TMS](https://en.wikipedia.org/wiki/Tile_Map_Service) tiles
- [x] Set up interim hosting for file assets/tiles
- [x] Organize polygon boundaries for regional summaries
- [x] Summarize layers in boundaries and set up file/DB hosting for backend

## Shiny UI

- [x] Set up golem package/project 
- [x] Use UI layout with a custom navbar (#2)
- [x] Full page Leaflet module (#3)
- [x] Compare 2 maps (#4)
- [x] Regional summaries (#5)
- [ ] Bird results
- [x] Caribou results
- [ ] Methods
- [x] Assets browser (#6)

## Documentation

- [x] Technical documentation of data processing steps (markdown)
- [x] Technical documentation of server setup, deployment, hosting, updating (markdown)
- [x] Technical documentation of Shiny package modules/functions (package documentation)
- [ ] End-user summary: how to use the app, how to interpret the results (part of the site/app)

## Deployment

- [x] Containerizing the Shiny app
- [x] Update [static files](https://github.com/PredictiveEcology/WesternBorealInitiative/tree/master/docs) on server (not `api` endpoints but `/`)
- [x] Edit Docker compose as needed
- [x] Update documentation

**Comment by psolymos** [comment]
Closing NWT related open issues
