### ISSUE TITLE
WBI full extent ROADMAP

### ISSUE THREAD

**Issue by psolymos** [PredictiveEcology/wbi_shiny#21]
# Code & CICD

- [x] GitHub repo structure revisions
- [x] GitHub Container Registry setup & access 
- [x] GitHub Action to build app images 

# Server setup

- [x] DRAC VM setup in Arbutus cloud
- [x] Migrate Docker compose & Caddy setup from DO instance
- [x] Set A record to wbi.predictiveecology.org to floating IP
- [x] Attach 5TB volume and mount for file server
- [x] Migrate TIF files from DO to Arbutus cloud

# Data processing

All years/scales/regions/scenarios for:

- [x] Bird maps
- [x] Leading tree species
- [x] Cumulative burn
- [x] Biomass
- [x] Regional summaries
- [ ] ~~Caribou~~

Pending QC:

- [x] Check maps
- [x] Review biomass/burn calculation & results

# Frontend

## File server

- [x] NWT files migrated from DO server to the Alliance instance
- [x] File server up-to-date for the `wbi` project

## NWT app
- [x] Update Dockerfile, dependencies
- [x] Add WBI logo and favicon
- [x] Test TIF based loading (not using tile server
- [x] Update app to v2 & deploy

## WBI full extent

- [x] Full extent map and selector updates
- [x] Side-by-side map comparison
- [x] Regional summaries
- [x] Table listing maps to download
- [x] Dockerize and deploy
- [ ] ~~Other~~

**Comment by psolymos** [comment]
Additional things to check:

- [ ] Need to remove full extent biomass & burn maps from file server
- [ ] Make the default map extent conditional on element/group
- [ ] Need to remove full extent biomass & burn options from the download tables

**Comment by psolymos** [comment]
## Outstanding tasks

#### Shiny app UI

- [ ] map & side-by-side inputs revision
- [ ] map & side-by-side keyboard shortcuts
- [ ] rename prod to landscape
- [ ] include `(bird)`/`(tree)` in the dropdown to make it searchable?

#### Lookup tables

- [ ] summarize how to update display text in lookup tables etc.
- [ ] explain how to add more regional summaries to the app

#### Deployment, testing, integration

- [ ] add package test to GH actions
- [ ] add docker image tests to GH actions
- [ ] add `--error` flag to littler installation steps
- [ ] add webhook to server to pull/update services
- [ ] update [WBI repo](https://github.com/PredictiveEcology/WesternBorealInitiative) with apps listing
- [ ] add webhook to server to pull/update static pages
